import Head from "next/head";
import styles from '../../styles/cartItems.module.css';
import MainNavigation from "@/components/Layout/mainNavigation";
import { useContext } from "react";
import { CartContext } from "@/context/cartContext";
import CartItem from "@/components/cartItems";

export default function Cart() {
     const {items} = useContext(CartContext);
     console.log(items);
     const cartSummary = () => {
        let total = 0;
        for (let i = 0; i < items.length; i++) {
            const item = items[i];
            total += item.price * item.quantity;
        }
        return total;
     }
     const totalPrice = cartSummary();
    return (
     <>
        <Head>
            <title>Cart</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
            <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet"/>
        </Head>
        <main className={styles.shop}>
            <MainNavigation/>
                {items.length === 0 && <p className={styles.emptyCart}>Cart Is Empty...</p>}
                 { items.length > 0 && <div className={styles.mainContent}>
                    <ul className={styles.productList}>
                        {items.map((prod) => {
                            return <li key={prod._id}><CartItem product={prod}/></li>
                        })}
                    </ul>
                    <div>
                        <div className={styles.cartSummary}>
                            <div>
                                <p>Subtotal</p>
                                <p>${totalPrice.toFixed(2)}</p>
                            </div>
                            <div>
                            <p>Discount</p>
                            <p>$0.00</p>
                            </div>
                            <hr></hr>
                            <div>
                            <h3>Grand total</h3>
                            <h3>${parseFloat(totalPrice).toFixed(2)}</h3>
                            </div>
                            <button>Checkout</button>
                        </div>
                    </div>
                </div>
                }
            
           
        </main>
     </>
  );
}
