import { Link } from 'next/link';
import Head from "next/head";
import styles from '../../styles/products.module.css';
import { PRODUCTS } from "@/data";
import MainNavigation from "../../components/Layout/mainNavigation";
import ProductItem from "@/components/productItem";
import { useContext, useState } from "react";
import { CartContext } from "@/context/cartContext";


export default function Products() {
    const [showFeedback, setShowFeedback] = useState(false);
    
    const handleShowFeedback = () => {
        setShowFeedback(true);
        setTimeout(() => {
            setShowFeedback(false)
        },3000)
    }
    const {items} = useContext(CartContext);
    console.log(items)
    return (
     <>
        <Head>
            <title>E-commerce</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="icon" href="/favicon.ico" />
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
            <link href="https://fonts.googleapis.com/css2?family=New+Amsterdam&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet"/>
        </Head>
        <main className={styles.shop}>
            <MainNavigation/>
            {showFeedback && <p className={styles.feedback}>Product Added</p>}
            <div className={styles.mainContent}>
                 <ul className={styles.productList}>
                    {PRODUCTS.map((prod) => {
                        return <li key={prod._id}><ProductItem product={prod} showFeedback={handleShowFeedback}/></li>
                    })}
                </ul>
            </div>
           
        </main>
     </>
  );
}

